### ISSUE TITLE
Missing template error when running "scaffold" command

### ISSUE THREAD

**Issue by bartronicus** [clevyr/scaffold#4]
v0.5.6 installed from homebrew
Running`scaffold` and selecting all the default options throws:
`panic: unable to read github.com/clevyr/scaffold:/templates/10-before-composer/nova-components/.gitkeep`
Can successfully scaffold an app by running `go run . -C /path/to/parentDir` from scaffold directory

**Comment by gabe565** [comment]
Thanks, this has been resolved in [v0.6.0](https://github.com/clevyr/scaffold/releases/tag/v0.6.0).
